### PR TITLE
generate cmake and bidder executable

### PR DESCRIPTION
**Pull request by venediktov**
work in progress need to rethink design of generators 
Would like to delegate a call directly from flags package when it processes "cache" , "app" or  "cmake" arguments

### CODE REVIEW

**Comment by venediktov** [comment]
something like this callback when flags is processing "cmake" , "app" or "cache"

**Comment by venediktov** [comment]
This pull request will close #5

**Comment by venediktov** [comment]
this PR  should also close #7

**Comment by venediktov** [comment]
I like your thinking , good to have compact and easy to use code!

**Comment by venediktov** [comment]
I changed map to array because the key is not used anyway. 
```for _, value := range stubs.TypeRegistry``` 
will work the same way for array as for map , love the way golang needs so little or no change :-)

**Comment by abushev** [comment]
Looks good, good work!

**Pull request merged**
